version: '3'

services:
  netopeer2:
    image: blueonap/netconf-pnp-simulator:v2.3.0
    container_name: mynetconf
    restart: always
    ports:
      - "830:830"
      - "6513:6513"
    volumes:
      - ./:/config/models/mynetconf
