version: '3'

services:
  netopeer2:
    image: quay.io/blue-onap/netconf-pnp-simulator:v2.7.0
    container_name: mynetconf
    restart: always
    ports:
      - "830:830"
      - "6513:6513"
    volumes:
      - ./:/config/modules/mynetconf
