name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  DOCKER_BUILDKIT: 1
  CONTAINER_PUSH_REGISTRY: quay.io
  LOCAL_IMAGE_TAG: netconf-pnp-simulator:latest
  REMOTE_IMAGE_TAG: quay.io/blue-onap/netconf-pnp-simulator:latest
  TRIVY_VERSION: 0.5.3

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image
      run: docker build -t $LOCAL_IMAGE_TAG -t $REMOTE_IMAGE_TAG --build-arg BUILDKIT_INLINE_CACHE=1 --cache-from $REMOTE_IMAGE_TAG --progress plain .

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install tox
      run: |
        python -m pip install --upgrade pip
        pip install tox

    - name: Run tests
      run: tox

    - name: Login to registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.CONTAINER_PUSH_REGISTRY }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Push to registry
      run: docker push $REMOTE_IMAGE_TAG

    - name: Install Trivy
      run: |
          wget https://github.com/aquasecurity/trivy/releases/download/v${TRIVY_VERSION}/trivy_${TRIVY_VERSION}_Linux-64bit.tar.gz
          tar xzf trivy_${TRIVY_VERSION}_Linux-64bit.tar.gz
          
    - name: Run Trivy
      run: ./trivy --exit-code 1 $LOCAL_IMAGE_TAG
